import test from 'node:test';
import assert from 'node:assert/strict';
import { Window } from 'happy-dom';
import { DEFAULTS, sanitizePreferences } from '../extension/config.js';
import { applyAppearance, bindAppearance, appearanceMarkup } from '../extension/appearance.js';

test('appearance controls preview, persist and reset actual layout preferences', async () => {
  const window = new Window();
  const player = window.document.createElement('div'), host = window.document.createElement('div');
  window.document.body.append(player); player.append(host);
  const root = host.attachShadow({ mode: 'open' });
  root.innerHTML = `<button id="reading-tab"></button><button id="appearance-tab"></button><div id="reading-settings"></div><button id="close"></button>${appearanceMarkup}<div id="subtitle-frame"><button id="done-layout"></button><button id="resize-handle"></button><button id="ratio-handle"></button></div>`;
  let prefs = { ...DEFAULTS }; const saved = [];
  const preview = patch => { prefs = { ...prefs, ...patch }; applyAppearance(host, root, prefs); };
  bindAppearance({ host, root, player, getPreferences: () => prefs, preview, save: patch => saved.push(patch) });
  preview({});
  root.getElementById('theme').value = 'mint'; root.getElementById('theme').onchange();
  assert.equal(host.dataset.theme, 'mint'); assert.deepEqual(saved.at(-1), { theme: 'mint' });
  root.getElementById('panelOpacity').value = '60'; root.getElementById('panelOpacity').oninput();
  assert.equal(host.style.getPropertyValue('--panel-alpha'), '0.6');
  root.getElementById('fontFamily').value = 'serif'; root.getElementById('fontFamily').onchange();
  assert.match(host.style.getPropertyValue('--subtitle-font'), /Georgia/);
  root.getElementById('translationColor').value = '#ffe088'; root.getElementById('translationColor').onchange();
  assert.equal(host.style.getPropertyValue('--translation-color'), '#ffe088');
  assert.deepEqual(saved.at(-1), { translationColor: '#ffe088' });
  root.getElementById('lineHeight').value = '1.7'; root.getElementById('lineHeight').onchange();
  assert.equal(host.style.getPropertyValue('--subtitle-line-height'), '1.7');
  root.getElementById('reset-style').click();
  assert.equal(prefs.fontFamily, DEFAULTS.fontFamily); assert.equal(prefs.translationColor, DEFAULTS.translationColor);
  root.getElementById('appearance-tab').click(); assert.equal(root.getElementById('reading-settings').hidden, true);
  const frame = root.getElementById('subtitle-frame');
  frame.setPointerCapture = () => {};
  player.getBoundingClientRect = () => ({ width: 1000, height: 500 });
  root.getElementById('edit-layout').click();
  assert.equal(frame.dataset.editing, 'true');
  const pointer = (name, target, x, y) => target.dispatchEvent(new window.PointerEvent(name, { clientX: x, clientY: y, pointerId: 1, button: 0, bubbles: true }));
  pointer('pointerdown', frame, 500, 400); pointer('pointermove', frame, 600, 300); pointer('pointerup', frame, 600, 300);
  assert.equal(prefs.subtitleX, 60); assert.equal(prefs.subtitleY, 68); assert.equal(saved.at(-1).subtitleX, 60);
  pointer('pointerdown', root.getElementById('resize-handle'), 500, 400); pointer('pointermove', frame, 580, 400); pointer('pointerup', frame, 580, 400);
  assert.equal(prefs.fontSize, 34);
  pointer('pointerdown', root.getElementById('ratio-handle'), 500, 400); pointer('pointermove', frame, 500, 450); pointer('pointerup', frame, 500, 450);
  assert.equal(prefs.translationScale, 1.4);
  root.getElementById('done-layout').click(); assert.equal(frame.dataset.editing, 'false');
  root.getElementById('reset-layout').click(); assert.equal(prefs.fontSize, 24); assert.equal(prefs.subtitleX, 50);
  const sanitized = sanitizePreferences({ fontSize: 999, subtitleX: -100, panelOpacity: 5, translationScale: 20, theme: 'invalid' });
  assert.equal(sanitized.fontSize, 64); assert.equal(sanitized.subtitleX, 10); assert.equal(sanitized.panelOpacity, 35); assert.equal(sanitized.translationScale, 1.8); assert.equal(sanitized.theme, 'midnight');
  const invalidStyle = sanitizePreferences({ fontFamily: 'url(https://evil.test/font)', originalColor: 'red;display:none', fontWeight: '999', lineHeight: 10 });
  assert.equal(invalidStyle.fontFamily, 'system'); assert.equal(invalidStyle.originalColor, '#ffffff');
  assert.equal(invalidStyle.fontWeight, '600'); assert.equal(invalidStyle.lineHeight, 2);
  await window.happyDOM.abort();
});
